#ifndef CONFIGLEDSHIFTREGISTER_H
#define CONFIGLEDSHIFTREGISTER_H

#define LED_1_RED       B00000001 
#define LED_1_GREEN     B00000010
#define LED_1_BLUE      B00000100
#define LED_1_ALL       LED_1_RED | LED_1_GREEN | LED_1_BLUE

#define LED_2_RED       B00001000
#define LED_2_GREEN     B00010000
#define LED_2_BLUE      B00100000
#define LED_2_ALL       LED_2_RED | LED_2_GREEN | LED_2_BLUE

//only 2 bits
#define LED_3_RED       B01000000
#define LED_3_GREEN     B10000000
#define LED_3_ALL       LED_3_RED | LED_3_GREEN

//WELL
#define LED_WELL_ALL        LED_1_ALL
#define LED_WELL_RED        LED_1_RED
#define LED_WELL_GREEN      LED_1_GREEN
#define LED_WELL_BLUE       LED_1_BLUE
#define LED_WELL_YELLOW     LED_1_RED | LED_1_GREEN
#define LED_WELL_MAGENTA    LED_1_RED | LED_1_BLUE
#define LED_WELL_CYAN       LED_1_GREEN |LED_1_BLUE
#define LED_WELL_WHITE      LED_1_RED | LED_1_GREEN | LED_1_BLUE

//TANK
#define LED_TANK_ALL        LED_2_ALL
#define LED_TANK_RED        LED_2_RED
#define LED_TANK_GREEN      LED_2_GREEN
#define LED_TANK_BLUE       LED_2_BLUE
#define LED_TANK_YELLOW     LED_2_RED | LED_2_GREEN
#define LED_TANK_MAGENTA    LED_2_RED | LED_2_BLUE
#define LED_TANK_CYAN       LED_2_GREEN |LED_2_BLUE
#define LED_TANK_WHITE      LED_2_RED | LED_2_GREEN | LED_2_BLUE

//PUMP
#define LED_PUMP_ALL        LED_3_ALL
#define LED_PUMP_RED        LED_3_RED
#define LED_PUMP_GREEN      LED_3_GREEN
#define LED_PUMP_YELLOW     LED_3_RED | LED_3_GREEN



#endif